name: Generate JSON File

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date (e.g., 2024/02/07)'
        required: false
      type:
        description: 'Type (e.g., 101)'
        required: false

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate File Name from Date
        id: generate_file_name
        run: |
          DATE=${{ github.event.inputs.date || '' }}
          if [ -z "$DATE" ]; then DATE=$(date +'%Y/%m/%d'); fi
          FORMATTED_DATE=$(echo "$DATE" | sed 's|/||g')
          BASE_FILE_NAME="Info/${FORMATTED_DATE}"
          FILE_NAME="${BASE_FILE_NAME}.json"
          TYPE=${{ github.event.inputs.type || '0' }}
          
          # Check if file exists and add version suffix if needed
          VERSION=2
          while [ -f "$FILE_NAME" ]; do
            FILE_NAME="${BASE_FILE_NAME}_v${VERSION}.json"
            VERSION=$((VERSION + 1))
          done
          
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV
          echo "JSON_DATE=${DATE}" >> $GITHUB_ENV
          echo "JSON_TYPE=${TYPE}" >> $GITHUB_ENV

      - name: Generate JSON File
        run: |
          JSON_CONTENT=$(cat <<EOF
          {
              "date": "${JSON_DATE}",
              "type": ${JSON_TYPE},
              "title": "",
              "outline": "",
              "description": "",
              "published": false
          }
          EOF
          )
          echo "$JSON_CONTENT" > $FILE_NAME

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add $FILE_NAME
          git commit -m "Add $FILE_NAME"
          git push
