name: Generate Release JSON File

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date (e.g., 2024/02/07)'
        required: false
      version:
        description: 'Version (e.g., 1.32.0)'
        required: true

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate File Name from Date
        id: generate_file_name
        run: |
          DATE=${{ github.event.inputs.date || '' }}
          if [ -z "$DATE" ]; then DATE=$(date +'%Y/%m/%d'); fi
          FORMATTED_DATE=$(echo "$DATE" | sed 's|/||g')
          FILE_NAME="Info/${FORMATTED_DATE}.json"
          VERSION=${{ github.event.inputs.version || '1.1' }}
          
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV
          echo "JSON_DATE=${DATE}" >> $GITHUB_ENV
          echo "JSON_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Generate JSON File
        run: |
          JSON_CONTENT=$(cat <<EOF
          {
              "date": "${JSON_DATE}",
              "type": 101,
              "title": "アプリのアップデート",
              "outline": "新しいバージョン ${JSON_VERSION} がリリースされました",
              "description": "**【アップデート内容】**\n- xxx\n\n**【バージョン】**\nバージョン：${JSON_VERSION}\nApp Store：[スペインゴ](https://apps.apple.com/jp/app/%E3%82%B9%E3%83%9A%E3%82%A4%E3%83%B3%E3%82%B4/id6469019716)",
              "published": false
          }
          EOF
          )
          echo "$JSON_CONTENT" > $FILE_NAME

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add $FILE_NAME
          git commit -m "Add $FILE_NAME"
          git push
